#ifndef MACRO_H
#define MACRO_H

#define WIN_HEIGHT 600
#define WIN_WIDTH 800

#define GRAPH_SCALE 30
#define ORIGIN_X GRAPH_SCALE*((WIN_WIDTH/GRAPH_SCALE)/2)
#define ORIGIN_Y GRAPH_SCALE*((WIN_HEIGHT/GRAPH_SCALE)/2)

#endif 
